AWSTemplateFormatVersion: 2010-09-09
Description: "Set GuardDuty alert"
Parameters:
  MailAddress:
    Description: Enter email address to send notification.
    Type: String
Resources:
  SNSTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      DisplayName: "MnGuardDutyTopic"
      TopicName: MnGuardDutyTopic
  SNSSubscription:
    Type: "AWS::SNS::Subscription"
    Properties:
      Endpoint: !Ref MailAddress
      Protocol: email
      TopicArn: !Ref SNSTopic
      Region: !Ref AWS::Region
  SNSTopicPolicy:
    Type: "AWS::SNS::TopicPolicy"
    Properties:
      PolicyDocument:
        Id: default_policy_ID
        Version: "2012-10-17"
        Statement:
          - Sid: default_statement_ID
            Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - "SNS:GetTopicAttributes"
              - "SNS:SetTopicAttributes"
              - "SNS:AddPermission"
              - "SNS:RemovePermission"
              - "SNS:DeleteTopic"
              - "SNS:Subscribe"
              - "SNS:ListSubscriptionsByTopic"
              - "SNS:Publish"
              - "SNS:Receive"
            Resource: !Ref SNSTopic
            Condition:
              StringEquals:
                "AWS:SourceOwner": !Ref "AWS::AccountId"
          - Sid: AWSEvents_AlertGuardDutyFindings_Id123
            Effect: Allow
            Principal:
              Service:
                - "events.amazonaws.com"
            Action: "sns:Publish"
            Resource: !Ref SNSTopic
      Topics:
        - !Ref SNSTopic
  EventsRule:
    Type: "AWS::Events::Rule"
    Properties:
      Name: MnGuardDutyFindingRule
      Description: "Alert to SNS topic when find threats by GuardDuty"
      EventPattern:
        { "source": ["aws.guardduty"], "detail-type": ["GuardDuty Finding"] }
      Targets:
        - Arn: !Ref SNSTopic
          Id: Id123
